### ISSUE TITLE
Is this how to import external `Js` from the body?

### ISSUE THREAD

**Issue by BroJenuel** [jakubsuplicki/multibox_menu_nuxt_js#4]
I have my js filies inside `assets/js/*.js` but when I tried to insert it cant be found.
![image](https://user-images.githubusercontent.com/31676163/109819003-90a65a00-7c6e-11eb-8744-38334697eb26.png)

This is my code:
![image](https://user-images.githubusercontent.com/31676163/109819058-9dc34900-7c6e-11eb-8ae5-d95b38f703c9.png)

**Comment by jakubsuplicki** [comment]
Please also include these files in your static folder. That is `static/js/*.js`.
Having it in both, assets and static folders should fix this error.

**Comment by jakubsuplicki** [comment]
To be honest you could just import these files in your static folder instead. That is `static/js/*.js`.
`nuxt.config.js` would not change. You would still import it the same way.

**Comment by BroJenuel** [comment]
> To be honest you could just import these files in your static folder instead. That is `static/js/*.js`.
> `nuxt.config.js` would not change. You would still import it the same way.

Thanks,, Sorry, I actually figured it out after an hour,, forgot to close this early.. but still, thanks for helping, :)
